---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность продолжать выбирать товары в каталоге, после добавление товара в корзину
  - Пользователь должен видеть в каталоге и на странице товара название, рейтинг, цена со скидкой и без нее
  - Пользователь должен иметь возможность удалять товар из корзины
  - Пользователь должен иметь возможность вернутся из корзины и продолжить выбирать товары из каталога
  - Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
non-functional:
  - Корзина должна хранится в сессии браузера
  - Cайт должен быть SPA
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
implicit:
  - Любая интеграция с платежной системой на сайте, должна выдерживать большое количество трафика
  - При посещении сайта , должно быть предупреждение об использовании сессий
  - Сайт должен быть кроссбраузерным